# ./devenv/opencode/default.nix

{ config, lib, ... }: {
  imports = [
    ./agent
    ./command
    ./mcp
    ./permission
    ./plugin
    ./skill
    ./tool
  ];

  opencode = {
    enable = true;

    settings = {
      provider = {
        lmstudio = {
          npm = "@ai-sdk/openai-compatible";
          name = "LM Studio";

          options = {
            baseURL = "http://127.0.0.1:1234/v1";
          };

          models = {
            "qwen3.6-27b" = {
              name = "Qwen 3.6 27B";
            };

            "qwen3.6-35b-a3b" = {
              name = "Qwen 3.6 35B A3B";
            };

            "qwen3.6-27b-mtp" = {
              name = "Qwen 3.6 27B MTP";
            };

            "qwen3.6-35b-a3b-mtp" = {
              name = "Qwen 3.6 35B A3B MTP";
            };

            "glm-4.7-flash" = {
              name = "GLM 4.7 Flash";
            };

            "gemma-4-31b-it" = {
              name = "Gemma 4 31B IT";
            };

            "nvidia-nemotron-3-nano-omni-30b-a3b-reasoning" = {
              name = "Nvidia Nemotron 3 Nano Omni 30B A3B Reasoning";
            };
          };
        };
      };

      compaction = {
        auto = true;
        prune = true;
      };

      plugin = [
        "file:${config.devenv.root}/modules/opencode-re"
        "oh-my-openagent@4.16.0"
      ];

      permission = {
        "*_idalib_switch" = "deny";
        "*_idalib_open" = "deny";
        "*_idalib_unbind" = "deny";
      };
    };

    rules = lib.strings.removeSuffix "\n" ''
      # OpenVB Reverse Engineering Rules

      - Treat this repository as a reverse-engineering and faithful reimplementation project for Fallout: Van Buren.

      ## IDA Target Selection

      - There are two distinct IDA MCP servers:
        - `ida_original_f3` contains the original proprietary F3 demo executable and is the authoritative reverse-engineering reference.
        - `ida_reimplementation_openvb` contains the rebuilt OpenVB reimplementation and is only a validation, comparison, and debugging target.
      - Default to `ida_original_f3` for reverse-engineering, behavior discovery, function identification, type recovery, control-flow analysis, constant recovery, calling-convention analysis, and documentation work.
      - Use `ida_reimplementation_openvb` only when the task explicitly requires inspecting, debugging, or validating the current reimplementation.
      - Never infer original behavior from `ida_reimplementation_openvb`. The reimplementation may be incomplete, incorrect, stubbed, or stale.
      - When comparing the two executables, inspect `ida_original_f3` first, record the original behavior, and only then inspect `ida_reimplementation_openvb`.
      - Never treat behavior observed in the reimplementation as proof of original behavior without independently confirming it in `ida_original_f3`.
      - Before invoking an IDA MCP tool, explicitly identify the intended target as either `ORIGINAL_REFERENCE` or `REIMPLEMENTATION_UNDER_TEST`.
      - If the intended target is ambiguous, use `ida_original_f3`.
      - Tool names containing `ida_original_f3` always operate on the original reference executable.
      - Tool names containing `ida_reimplementation_openvb` always operate on the reimplementation under test.
      - Never substitute one IDA MCP server for the other because an address, symbol, function name, or apparent implementation looks similar.

      ## Project and Database Rules

      - Treat the original demo and rebuilt reimplementation as two explicit analysis and debugging targets that can be compared at multiple fidelity levels.
      - The canonical original database is `./artifacts/F3.exe.i64`.
      - The canonical reimplementation database path is `./build/F3.exe.i64`.
      - The reimplementation IDA database (`$OPENVB_REIMPL_IDB`) is ephemeral: it is deleted before each MSVC rebuild and regenerated by IDA from the fresh executable on the next server start.
      - Do not rely on the reimplementation IDA database persisting across builds.
      - For persistent metadata, use the original IDB or the opencode-openje ledger.
      - Use the headless `ida_original_f3` and `ida_reimplementation_openvb` MCP servers rather than assuming a live GUI plugin session.
      - Open or verify the intended original or reimplementation database explicitly before analyzing, comparing, debugging, or curating.
      - Do not rely solely on the currently open database to determine the target; verify the MCP server name as well.

      ## Analysis Rules

      - Prefer evidence from the codebase, documentation, and the correct IDA MCP target over inference or guesswork.
      - When analyzing binary behavior, separate confirmed findings from hypotheses and open questions.
      - Escalate comparison from binary surface to structure, types, pseudocode, and runtime checkpoints only when needed.
      - Use `ida_original_f3` to inspect original decompilation, disassembly, xrefs, types, globals, strings, constants, and comments before proposing behavior changes.
      - Use `ida_reimplementation_openvb` afterward only when comparison against the current implementation is necessary.
      - Safe metadata curation in the repo-specific reimplementation IDA database is allowed; binary patching and arbitrary IDAPython are not default workflow steps.
      - Treat function analysis as bounded graph traversal with memoized summaries, not unbounded recursive delegation.
      - Detect repeated nodes, recursion, and SCC-like cycles before descending further.
      - Use bounded verification loops to refine summaries before propagating conclusions upward.
      - Keep the reimplementation aligned with behavior observed in `ida_original_f3` rather than rewriting for cleanliness.
      - Update repository documentation such as `docs/f3/*` when analysis produces durable findings.
      - Preserve the existing Windows/MSVC build assumptions and avoid introducing unrelated tooling changes.

      ## Debugging Rules

      - Debugger tools are built into both IDA MCP servers because `?ext=dbg` is permanently enabled.
      - Use debugger tools exposed by `ida_original_f3` only to debug the original F3 executable.
      - Use debugger tools exposed by `ida_reimplementation_openvb` only to debug the rebuilt OpenVB executable.
      - Never use debugger tools from one MCP server while reasoning about runtime state from the other target.
      - Start the debugging session with `dbg_start()` on the IDA MCP server corresponding to the intended target.
      - Always end debugging sessions with `dbg_exit()` on that same MCP server.
      - Only one debugging session may be active per IDA MCP instance at a time.
      - The original and reimplementation may be debugged independently because they use separate IDA MCP instances.
      - Pair debugging with static analysis on the same target: use `decompile()` or `disasm()` before setting breakpoints with `dbg_add_bp()`.
      - Confirm that breakpoint addresses came from the same executable and current IDA database as the active debugger session.
      - Debugger state, breakpoints, runtime addresses, and process state do not persist across debugger sessions.
      - Re-acquire reimplementation addresses and recreate breakpoints after every rebuild because the executable and its IDA database may have changed.
      - After rebuilding the reimplementation executable, refresh only `ida_reimplementation_openvb` with `idalib_close()` followed by `idalib_open()`.
      - Do not refresh `ida_original_f3` after reimplementation builds; the original F3 executable and its database are static.
      - Do not restart or manage a separate GDB stub unless the actual IDA MCP debugger reports that an external debugger backend is required.
    '';

  };
}
