# ./devenv/opencode/default.nix

{ config, lib, ... }: {
  imports = [
    ./agent
    ./command
    ./mcp
    ./permission
    ./plugin
    ./skill
  ];

  opencode = {
    enable = true;

    settings = {
      provider = {
        lmstudio = {
          npm = "@ai-sdk/openai-compatible";
          name = "LM Studio";

          options = {
            baseURL = "http://127.0.0.1:1234/v1";
          };

          models = {
            "qwen3.6-27b" = {
              name = "Qwen 3.6 27B";
            };

            "qwen3.6-35b-a3b" = {
              name = "Qwen 3.6 35B A3B";
            };

            "glm-4.7-flash" = {
              name = "GLM 4.7 Flash";
            };

            "gemma-4-31b-it" = {
              name = "Gemma 4 31B IT";
            };

            "nvidia-nemotron-3-nano-omni-30b-a3b-reasoning" = {
              name = "Nvidia Nemotron 3 Nano Omni 30B A3B Reasoning";
            };
          };
        };
      };

      compaction = {
        auto = true;
        prune = true;
      };

      plugin = [
        "file:${config.devenv.root}/modules/opencode-openje"
        "oh-my-openagent@4.0.0"
      ];
    };

    rules = lib.strings.removeSuffix "\n" ''
      # OpenVB Reverse Engineering Rules

      - Treat this repository as a reverse-engineering and faithful reimplementation project for Fallout: Van Buren.
      - Treat the original demo and rebuilt reimplementation as two explicit analysis/debug targets that can be compared at multiple fidelity levels.
      - The canonical original database is `./F3.exe.i64` and the canonical reimplementation database path is `./.devenv/state/ida/F3-reimpl.i64`.
      - The reimplementation IDA database (`$OPENVB_REIMPL_IDB`) is ephemeral — it is deleted before each MSVC rebuild and regenerated by IDA from the fresh EXE on next server start. Do not rely on it persisting across builds. For persistent metadata, use the original IDB or the opencode-openje ledger.
      - Use the headless orig/reimpl IDA MCP servers rather than assuming a live GUI plugin session.
      - Open the intended original or reimplementation database explicitly before analyzing, comparing, debugging, or curating.
      - Prefer evidence from the codebase, docs, and IDA MCP over inference or guesswork.
      - When analyzing binary behavior, separate confirmed findings from hypotheses and open questions.
      - Escalate comparison from binary surface to structure, types, pseudocode, and runtime checkpoints only when needed.
      - Use IDA MCP tools to inspect decompilation, disassembly, xrefs, types, and comments before proposing behavior changes.
      - Safe metadata curation in the repo-specific reimplementation IDA database is allowed; binary patching and arbitrary IDAPython are not default workflow steps.
      - Treat function analysis as bounded graph traversal with memoized summaries, not unbounded recursive delegation.
      - Detect repeated nodes, recursion, and SCC-like cycles before descending further.
      - Use bounded verification loops to refine summaries before propagating conclusions upward.
      - Keep the reimplementation aligned with observed binary behavior rather than rewriting for cleanliness.
      - Update repository documentation such as `docs/f3/*` when analysis produces durable findings.
      - Preserve the existing Windows/MSVC build assumptions and avoid introducing unrelated tooling changes.
      - Debugger tools are always available on the IDA MCP servers (`?ext=dbg` is permanently enabled).
      - Before starting a debug session, ensure the Wine GDB stub process is running (`ida-orig-gdb` or `ida-reimpl-gdb`). Use `dbg_start()` on the appropriate MCP server to connect IDA to the remote GDB stub.
      - Always end debug sessions with `dbg_exit()` to detach cleanly. The GDB stub process remains running for future sessions.
      - Only one debug session per IDA instance at a time. The original and reimplementation cannot be debugged simultaneously through the same MCP server.
      - Pair debugging with static analysis: use `decompile` or `disasm` to find addresses before setting breakpoints with `dbg_add_bp()`.
      - Debugger state does not persist. The reimplementation IDB is ephemeral — re-acquire addresses after rebuilds.
      - After rebuilding the reimplementation EXE, refresh the IDA MCP session with `idalib_close()` + `idalib_open()` — no process restart needed. Restart the GDB stub with `devenv processes restart ida-reimpl-gdb`.
      - The original IDA MCP and GDB stub (`ida-orig-*`) never need refresh — `F3.exe` is static.
    '';
  };
}
