# ./devenv/opencode/default.nix

{ config, lib, ... }: {
  imports = [
    ./agent
    ./command
    ./mcp
    ./permission
    ./plugin
    ./skill
    ./tool
  ];

  opencode = {
    enable = true;

    settings = {
      provider = {
        lmstudio = {
          npm = "@ai-sdk/openai-compatible";
          name = "LM Studio";

          options = {
            baseURL = "http://127.0.0.1:1234/v1";
          };

          models = {
            "qwen3.6-27b" = {
              name = "Qwen 3.6 27B";
            };

            "qwen3.6-35b-a3b" = {
              name = "Qwen 3.6 35B A3B";
            };

            "qwen3.6-27b-mtp" = {
              name = "Qwen 3.6 27B MTP";
            };

            "qwen3.6-35b-a3b-mtp" = {
              name = "Qwen 3.6 35B A3B MTP";
            };

            "glm-4.7-flash" = {
              name = "GLM 4.7 Flash";
            };

            "gemma-4-31b-it" = {
              name = "Gemma 4 31B IT";
            };

            "nvidia-nemotron-3-nano-omni-30b-a3b-reasoning" = {
              name = "Nvidia Nemotron 3 Nano Omni 30B A3B Reasoning";
            };
          };
        };
      };

      compaction = {
        auto = true;
        prune = true;
      };

      plugin = [
        "file:${config.devenv.root}/modules/opencode-re"
        "oh-my-openagent@4.16.0"
      ];

      permission = {
        "*_idalib_switch" = "deny";
        "*_idalib_open" = "deny";
        "*_idalib_unbind" = "deny";
      };
    };

    rules = lib.strings.removeSuffix "\n" ''
      # OpenVB Reverse Engineering Rules

      - Treat this repository as a reverse-engineering and faithful reimplementation project for Fallout: Van Buren.

      ## IDA Target Selection

      - There are two distinct IDA MCP servers:
        - `ida_original_f3` is the original proprietary F3 demo executable and is the authoritative reverse-engineering reference.
        - `ida_reimplementation_openvb` is the rebuilt OpenVB reimplementation and is only a validation, comparison, and debugging target.
      - Default to `f3_exe_ida` for all reverse-engineering, behavior discovery, function identification, type recovery, control-flow analysis, constant recovery, calling-convention analysis, and documentation work.
      - Use `openvb_exe_ida` only when the task explicitly requires inspecting, debugging, or validating the current reimplementation.
      - Never infer original behavior from `openvb_exe_ida`. The reimplementation may be incomplete, incorrect, stubbed, or stale.
      - When comparing the two executables, inspect `f3_exe_ida` first, record the original behavior, and only then inspect `openvb_exe_ida`.
      - Never treat matching behavior in the reimplementation as proof of original behavior without independently confirming it in `f3_exe_ida`.
      - Before invoking an IDA MCP tool, explicitly identify the intended target as either `ORIGINAL_REFERENCE` or `REIMPLEMENTATION_UNDER_TEST`.
      - If the intended target is ambiguous, use `f3_exe_ida`.
      - Tool names containing `f3_exe_ida` always refer to the original reference executable.
      - Tool names containing `openvb_exe_ida` always refer to the reimplementation under test.

      ## Project and Database Rules

      - Treat the original demo and rebuilt reimplementation as two explicit analysis/debug targets that can be compared at multiple fidelity levels.
      - The canonical original database is `./artifacts/F3.exe.i64`.
      - The canonical reimplementation database path is `./build/F3.exe.i64`.
      - The reimplementation IDA database (`$OPENVB_REIMPL_IDB`) is ephemeral: it is deleted before each MSVC rebuild and regenerated by IDA from the fresh EXE on the next server start.
      - Do not rely on the reimplementation IDA database persisting across builds.
      - For persistent metadata, use the original IDB or the opencode-openje ledger.
      - Use the headless original and reimplementation IDA MCP servers rather than assuming a live GUI plugin session.
      - Open the intended original or reimplementation database explicitly before analyzing, comparing, debugging, or curating.

      ## Analysis Rules

      - Prefer evidence from the codebase, documentation, and the correct IDA MCP target over inference or guesswork.
      - When analyzing binary behavior, separate confirmed findings from hypotheses and open questions.
      - Escalate comparison from binary surface to structure, types, pseudocode, and runtime checkpoints only when needed.
      - Use `f3_exe_ida` tools to inspect original decompilation, disassembly, xrefs, types, and comments before proposing behavior changes.
      - Use `openvb_exe_ida` afterward only when comparison against the current implementation is necessary.
      - Safe metadata curation in the repo-specific reimplementation IDA database is allowed; binary patching and arbitrary IDAPython are not default workflow steps.
      - Treat function analysis as bounded graph traversal with memoized summaries, not unbounded recursive delegation.
      - Detect repeated nodes, recursion, and SCC-like cycles before descending further.
      - Use bounded verification loops to refine summaries before propagating conclusions upward.
      - Keep the reimplementation aligned with behavior observed in `f3_exe_ida` rather than rewriting for cleanliness.
      - Update repository documentation such as `docs/f3/*` when analysis produces durable findings.
      - Preserve the existing Windows/MSVC build assumptions and avoid introducing unrelated tooling changes.

      ## Debugging Rules

      - Debugger tools are always available on both IDA MCP servers because `?ext=dbg` is permanently enabled.
      - Use `ida-orig-gdb` with `f3_exe_ida`.
      - Use `ida-reimpl-gdb` with `openvb_exe_ida`.
      - Never connect an IDA MCP server to the other target's GDB stub.
      - Before starting a debug session, ensure the corresponding Wine GDB stub process is running.
      - Use `dbg_start()` on the matching MCP server to connect IDA to its remote GDB stub.
      - Always end debug sessions with `dbg_exit()` to detach cleanly. The GDB stub process remains running for future sessions.
      - Only one debug session may run per IDA instance at a time.
      - Pair debugging with static analysis: use `decompile` or `disasm` on the same MCP server to find addresses before setting breakpoints with `dbg_add_bp()`.
      - Debugger state does not persist.
      - Re-acquire reimplementation addresses after every rebuild because its IDB is ephemeral.
      - After rebuilding the reimplementation EXE, refresh only `openvb_exe_ida` with `idalib_close()` followed by `idalib_open()`; no MCP process restart is needed.
      - After rebuilding, restart its GDB stub with `devenv processes restart ida-reimpl-gdb`.
      - The original IDA MCP server and GDB stub (`f3_exe_ida` and `ida-orig-gdb`) do not require refresh because the original `F3.exe` is static.
    '';
  };
}
